version: '3.7'
services:

  db:
    image: "postgres:12.2"
    volumes:
      - type: volume
        source: ktor-starter-data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "ktor-starter"

  web:
    image: my-application
    depends_on:
      - db
    ports:
      - "4000:8080"
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://db:5432/ktor-starter"
      JDBC_DATABASE_USER: "test"
      JDBC_DATABASE_PASSWORD: "password"

  # SQL admin
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8079:8080"

volumes:
  ktor-starter-data:
